#!/bin/bash

# Autor: Nido
# Versao: 1.0
# BSD-3-Clause License 
# Extrai o codigo do jogo e renomea, para o usar no OPL
#

slus=$(grep -Ea -o -m 1 "([A-Z]{4}\_[0-9]{1,3}\.[0-9]{1,3})" "${1}")
new="${slus}.${1}"
printf '%s\n' "Antigo nome: ${1}"
printf '%s\n' "ID: ${slus}"
printf '%s\n' "Novo nome: ${new}"
mv "$1" "$new"
